config/routes.rb
Rails.application.routes.draw do
  resources :normas
  resources :categoria_normas
  devise_for :users
  resources :posts
  resources :images
  root to: 'welcome#index'
  
  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      resources :images
      post "sign_up" => 'registration#create'
    end
  end


end

app/models/norma.rb
class Norma < ApplicationRecord
  belongs_to :categoria_normas
end

app/controllers/normas_controller.rb
class NormasController < ApplicationController
  before_action :set_norma, only: [:show, :edit, :update, :destroy]

  # GET /normas
  # GET /normas.json
  def index
    @normas = Norma.all
  end

  # GET /normas/1
  # GET /normas/1.json
  def show
  end

  # GET /normas/new
  def new
    @norma = Norma.new
  end

  # GET /normas/1/edit
  def edit
  end

  # POST /normas
  # POST /normas.json
  def create
    @norma = Norma.new(norma_params)

    respond_to do |format|
      if @norma.save
        format.html { redirect_to @norma, notice: 'Norma was successfully created.' }
        format.json { render :show, status: :created, location: @norma }
      else
        format.html { render :new }
        format.json { render json: @norma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /normas/1
  # PATCH/PUT /normas/1.json
  def update
    respond_to do |format|
      if @norma.update(norma_params)
        format.html { redirect_to @norma, notice: 'Norma was successfully updated.' }
        format.json { render :show, status: :ok, location: @norma }
      else
        format.html { render :edit }
        format.json { render json: @norma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /normas/1
  # DELETE /normas/1.json
  def destroy
    @norma.destroy
    respond_to do |format|
      format.html { redirect_to normas_url, notice: 'Norma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_norma
      @norma = Norma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def norma_params
      params.require(:norma).permit(:descripcion, :img_vid, :tipo, :categoria_normas_id)
    end
end

app/helpers/normas_helper.rb
module NormasHelper
end

app/views/normas/_form.html.erb
<%= form_with(model: norma, local: true) do |form| %>
  <% if norma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(norma.errors.count, "error") %> prohibited this norma from being saved:</h2>

      <ul>
      <% norma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :norma_descripcion %>
  </div>

  <div class="field">
    <%= form.label :img_vid %>
    <%= form.text_field :img_vid, id: :norma_img_vid %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :norma_tipo %>
  </div>

  <div class="field">
    <%= form.label :categoria_normas_id %>
    <%= form.text_field :categoria_normas_id, id: :norma_categoria_normas_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/normas/edit.html.erb
<h1>Editing Norma</h1>

<%= render 'form', norma: @norma %>

<%= link_to 'Show', @norma %> |
<%= link_to 'Back', normas_path %>

app/views/normas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Normas</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Img vid</th>
      <th>Tipo</th>
      <th>Categoria normas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @normas.each do |norma| %>
      <tr>
        <td><%= norma.descripcion %></td>
        <td><%= norma.img_vid %></td>
        <td><%= norma.tipo %></td>
        <td><%= norma.categoria_normas %></td>
        <td><%= link_to 'Show', norma %></td>
        <td><%= link_to 'Edit', edit_norma_path(norma) %></td>
        <td><%= link_to 'Destroy', norma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Norma', new_norma_path %>

app/views/normas/new.html.erb
<h1>New Norma</h1>

<%= render 'form', norma: @norma %>

<%= link_to 'Back', normas_path %>

app/views/normas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @norma.descripcion %>
</p>

<p>
  <strong>Img vid:</strong>
  <%= @norma.img_vid %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @norma.tipo %>
</p>

<p>
  <strong>Categoria normas:</strong>
  <%= @norma.categoria_normas %>
</p>

<%= link_to 'Edit', edit_norma_path(@norma) %> |
<%= link_to 'Back', normas_path %>