config/routes.rb
Rails.application.routes.draw do
  resources :normas
  resources :categoria_normas
  devise_for :users
  resources :posts
  resources :images
  root to: 'welcome#index'
  
  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      resources :images
      post "sign_up" => 'registration#create'
    end
  end


end

app/models/categoria_norma.rb
class CategoriaNorma < ApplicationRecord
end

app/controllers/categoria_normas_controller.rb
class CategoriaNormasController < ApplicationController
  before_action :set_categoria_norma, only: [:show, :edit, :update, :destroy]

  # GET /categoria_normas
  # GET /categoria_normas.json
  def index
    @categoria_normas = CategoriaNorma.all
  end

  # GET /categoria_normas/1
  # GET /categoria_normas/1.json
  def show
  end

  # GET /categoria_normas/new
  def new
    @categoria_norma = CategoriaNorma.new
  end

  # GET /categoria_normas/1/edit
  def edit
  end

  # POST /categoria_normas
  # POST /categoria_normas.json
  def create
    @categoria_norma = CategoriaNorma.new(categoria_norma_params)

    respond_to do |format|
      if @categoria_norma.save
        format.html { redirect_to @categoria_norma, notice: 'Categoria norma was successfully created.' }
        format.json { render :show, status: :created, location: @categoria_norma }
      else
        format.html { render :new }
        format.json { render json: @categoria_norma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria_normas/1
  # PATCH/PUT /categoria_normas/1.json
  def update
    respond_to do |format|
      if @categoria_norma.update(categoria_norma_params)
        format.html { redirect_to @categoria_norma, notice: 'Categoria norma was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria_norma }
      else
        format.html { render :edit }
        format.json { render json: @categoria_norma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_normas/1
  # DELETE /categoria_normas/1.json
  def destroy
    @categoria_norma.destroy
    respond_to do |format|
      format.html { redirect_to categoria_normas_url, notice: 'Categoria norma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria_norma
      @categoria_norma = CategoriaNorma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_norma_params
      params.require(:categoria_norma).permit(:descripcion)
    end
end

app/helpers/categoria_normas_helper.rb
module CategoriaNormasHelper
end

app/views/categoria_normas/_form.html.erb
<%= form_with(model: categoria_norma, local: true) do |form| %>
  <% if categoria_norma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categoria_norma.errors.count, "error") %> prohibited this categoria_norma from being saved:</h2>

      <ul>
      <% categoria_norma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :categoria_norma_descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categoria_normas/edit.html.erb
<h1>Editing Categoria Norma</h1>

<%= render 'form', categoria_norma: @categoria_norma %>

<%= link_to 'Show', @categoria_norma %> |
<%= link_to 'Back', categoria_normas_path %>

app/views/categoria_normas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categoria Normas</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria_normas.each do |categoria_norma| %>
      <tr>
        <td><%= categoria_norma.descripcion %></td>
        <td><%= link_to 'Show', categoria_norma %></td>
        <td><%= link_to 'Edit', edit_categoria_norma_path(categoria_norma) %></td>
        <td><%= link_to 'Destroy', categoria_norma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoria Norma', new_categoria_norma_path %>

app/views/categoria_normas/new.html.erb
<h1>New Categoria Norma</h1>

<%= render 'form', categoria_norma: @categoria_norma %>

<%= link_to 'Back', categoria_normas_path %>

app/views/categoria_normas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @categoria_norma.descripcion %>
</p>

<%= link_to 'Edit', edit_categoria_norma_path(@categoria_norma) %> |
<%= link_to 'Back', categoria_normas_path %>