config/routes.rb
Rails.application.routes.draw do
  resources :normas
  resources :categoria_normas
  devise_for :users
  resources :posts
  resources :images
  root to: 'welcome#index'
  
  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      resources :images
      post "sign_up" => 'registration#create'
    end
  end


end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader
    belongs_to :user

end

app/controllers/api/v1/images_controller.rb
module Api
    module V1
        class ImagesController < ApiApplicationController
        
            before_action :authenticate_request!

            def index
                images = Image.order('created_at DESC');
                render json: {status: 'SUCCESS', message: 'Carga de imagenes', data: images}, status: :ok
            end

            def show
                image = Image.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Carga la imagen', data: image}, status: :ok
            end

            def create
                image = Image.new(image_params)
                if image.save
                    render json: {status: 'SUCCESS', message: 'imagen guardada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no guardada', data: image}, status: :unprocessable_entity
                end
            end
                
            def destroy
                image = Image.find(params[:id])
                image.destroy
                render json: {status: 'SUCCESS', message: 'imagen eliminada', data: image}, status: :ok
            end

            def update
                image = Image.find(params[:id])
                if image.update_attributes(image_params)
                    render json: {status: 'SUCCESS', message: 'imagen editada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no editada', data: image}, status: :unprocessable_entity              
                end
            end
                
            private
                
            def image_params
                params.permit(:description, :picture)
            end

        end
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

    before_action :set_image, only: [:show, :edit, :update, :destroy]

    def index
        @images = Image.where user_id: current_user.id
        #ahora hacemos la consulta por medio del id del usuario
 
    end 

    def show 
       
    end 

    def new
        @image = Image.new
    end

    def edit 
       
    end    

    def create
        @image = current_user.images.new images_params
        @image.save
        redirect_to '/'
    end

    def update
        @image.update images_params 
        redirect_to @image
    end 

    def destroy
        @image.destroy
        redirect_to images_path 
    end

    private

# Never trust parameters from the scary internet, only allow the white list through.
    def images_params
        params.require(:image).permit :description, :picture
    end

    def set_image
        @image = Image.find params[:id]
    end 
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<div class="form-group">
    <%= form_for @image, :html => {:multipart => true} do |f|  %>
    <%= f.label :description %> <br>
    <%= f.text_field :description, class: 'form-control' %>
    <br>
    <%= f.label 'Cargar Imagen ' %> 
    <%= f.file_field :picture, class: 'form-control-file' %>
    <br>
    <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
    <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-4">
    <figure class="figure">
        <%= image_tag image.picture.medium.url, class: 'figure-img img-fluid rounded' %>
        <figcaption class="figure-caption">
            <%= image.description %>
            <%= link_to 'Editar', edit_image_path(image) %>
            <%= link_to 'Eliminar', image, method: :delete, data:{
            confirm: 'Esta seguro que decea eliminar esta imagen.'
            } %>
        </figcaption>
    </figure>
</div>

app/views/images/edit.html.erb
<h1>EDITAR IMAGENES</h1>
<%= render 'form'%>

app/views/images/index.html.erb
<div class="row">
    <%= render @images %>
</div>

app/views/images/new.html.erb
<h1>Nueva Imagen</h1>

<%= render 'form' %>

app/views/images/show.html.erb
<div class="row">
    <%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
    <%= @image.description %>
</div>